# Generated by Django 4.2.20 on 2025-05-24 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goldenqa', '0002_question_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Downvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='likes',
        ),
        migrations.AlterField(
            model_name='question',
            name='tag',
            field=models.CharField(choices=[('daily_life', 'Daily Life'), ('sports', 'Sports'), ('hobbies', 'Hobbies'), ('technology', 'Technology'), ('education_career', 'Education and Career'), ('health_fitness', 'Health and Fitness'), ('travel', 'Travel'), ('entertainment', 'Entertainment'), ('food_cooking', 'Food and Cooking'), ('music_arts', 'Music and Arts'), ('books_literature', 'Books and Literature'), ('relationships', 'Relationships'), ('gaming', 'Gaming'), ('science_nature', 'Science and Nature'), ('philosophy', 'Philosophy'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.AddField(
            model_name='upvote',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvote_set', to='goldenqa.answer'),
        ),
        migrations.AddField(
            model_name='upvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='downvote',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downvote_set', to='goldenqa.answer'),
        ),
        migrations.AddField(
            model_name='downvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
